---
- name: Set MySQL root password before installing
  debconf:
    name: mysql-server
    question: "{{ item }}"
    value: "{{ wordpress_mysql_root_pass | quote }}"
    vtype: password
  with_items:
    - mysql-server/root_password
    - mysql-server/root_password_again

- name: Install LAMP
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ wordpress_packages }}"

- name: "Delete {{ wordpress_document_root_index }}"
  file:
    path: "{{ wordpress_document_root_index }}"
    state: absent

- name: Check if wordpress is installed
  stat:
    path: "{{ wordpress_root_path }}"
  register: check_wordpress
