---
- name: Change root document on Apache
  lineinfile:
    dest: "{{ wordpress_apache_default_config_file }}"
    regexp: DocumentRoot .*
    line: "        DocumentRoot {{ wordpress_root_path }}"
  become: yes
  notify: Restart Apache
