---
- name: Change root document on Apache
  lineinfile:
    dest: "{{ wordpress_apache_default_config_file }}"
    regexp: DocumentRoot .*
    line: "        DocumentRoot {{ wordpress_root_path }}"
  notify: Restart Apache

- name: Create wordpress database
  mysql_db:
    name: "{{ wordpress_database_name }}"
    state: present
    login_user: "{{ wordpress_mysql_root_user }}"
    login_password: "{{ wordpress_mysql_root_pass }}"

- name: Check if wp-config.php exists
  stat:
    path: "{{ wordpress_config_path }}"
  register: check_wordpress_config

- name: Copy wp-config.php template
  template:
    src: wp-config.php.j2
    dest: "{{ wordpress_config_path }}"
  when: not check_wordpress_config.stat.exists
