---
- name: Install LAMP
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ wordpress_packages }}"
  become: yes

- name: "Delete {{ wordpress_document_root_index }}"
  file:
    path: "{{ wordpress_document_root_index }}"
    state: absent
  become: yes

- name: Check if wordpress is installed
  stat:
    path: "{{ wordpress_root_path }}"
  register: check_wordpress
